
server: 
    port: 8082
encrypt:
    key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
    security:
       user:
        name: vandana
        password: vandana

    cloud:
        config:
         server:
            git:
                uri: https://github.com/vandana123-c/spring-cloudconfig-wa-tolls-1o
                search-paths:
                - station*

                repos:
                    perf:
                      pattern: "*/perf"
                      uri: https://github.com/vandana123-c/spring-cloudconfig-wa-tools-perf
                      search-paths:
                      - "station*"  


 